repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--line-length=125]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: utility-repo-scripts/ensure_venv.sh
        language: script
        types: [python]
        exclude: ^alembic/
        args: [pylint, -v, --rcfile=.pylintrc]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.4'
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.34.0'
    hooks:
      - id: eslint
        files: \.[jt]sx?$|\.vue$ # *.js, *.jsx, *.ts, *.tsx and *.vue
        types: [file]
        additional_dependencies:
          - '@rushstack/eslint-patch@^1.2.0'
          - '@vue/eslint-config-prettier@^7.0.0'
          - '@vue/eslint-config-typescript@^11.0.2'
          - 'eslint@^8.33.0'
          - 'eslint-plugin-cypress@^2.12.1'
          - 'eslint-plugin-vue@^9.9.0'
