name: Python 3.10

on: [push, pull_request]

env:
  PYTHON_VERSION: "3.10"
  LINT_PATHS: >
    manage.py
    budgeting_tool
  SECRET_KEY: github actions fake secret key
  DEBUG: False

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Install Dependencies
        run: pip-sync requirements-test.txt requirements.txt

      - name: Flake8
        run: flake8 ${{ env.LINT_PATHS }}

      - name: Pylint
        run: pylint ${{ env.LINT_PATHS }}

      - name: Django Test
        run: python manage.py test
